baseURL = 'https://minimalistcss.github.io/'
languageCode = 'en-us'
paginate = 8
summaryLength = 8
theme = "hugo-theme-learn"
title = 'MinimalistCSS'

[markup.goldmark.renderer]
unsafe = true

[menu]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[[menu.main]]
identifier = "docs"
name = "Docs"
pre = "<i class='fa fa-heart'></i>"
url = "/docs/"
weight = 5

[[menu.second]]
identifier = "contact"
name = "Contact"
url = "https://github.com/The-Repo-Club/Feedback/issues/new"
weight = 1
[[menu.second]]
identifier = "privacy"
name = "Privacy"
url = "/privacy"
weight = 2

[params]
author = "Wayne Wesley"
description = "Hello there, I’m Wayne Wesley aka The-Repo-Club"
themeVariant = "blue"
menu_item_separator = " - "

[[params.social]]
icon = "github"
name = "Github"
url = "https://github.com/MinimalistCSS"
[[params.social]]
icon = "rss"
name = "RSS Feed"
url = "/index.xml"

[outputs]
home = ["HTML", "RSS", "JSON"]
